name: my_common_ui
description: My Design System
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  collection: ^1.17.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  list_diff: ^2.0.1
  lottie: ^2.2.0
  meta: ^1.8.0
  shimmer: ^3.0.0
